project:
  type: website
  output-dir: _site

website:
  title: "Observatorio de Legitimidad"
  navbar:
    left:
      - href: index.html
        text: Inicio
      - href: content/noticias/index.html
        text: Noticias
      - href: content/eventos/index.html
        text: Eventos
      - href: content/proyectos/index.html
        text: Proyectos

format:
  html:
    theme: 
      - default
    css: style.css
    toc: false
    code-fold: false
    embed-resources: true
    standalone: true
    navbar: false
    sidebar: false
    footer: false

